version: '1.0'

services:
  mysql:
    image: blog-mysql:latest
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 15896302145.saA
      MYSQL_DATABASE: blog
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  backend:
    image: blog-server:latest
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 15896302145.saA
      DB_NAME: blog

  nginx:
    image: blog-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
